@Back_HostAddress = https://localhost:44320

POST {{Back_HostAddress}}/api/patients
Content-Type: application/json

{
  "firstName": "TestNone",
  "lastName": "Test",
  "dateOfBirth": "1966-12-31",
  "gender": "Femme",
  "address": "1 Brookside St",
  "phoneNumber": "100-222-3333"
}
###
POST {{Back_HostAddress}}/api/patients
Content-Type: application/json
{
  "firstName": "TestBorderline",
  "lastName": "Test",
  "dateOfBirth": "1945-06-24",
  "gender": "Homme",
  "address": "2 High St",
  "phoneNumber": "200-333-4444"
}
###
POST {{Back_HostAddress}}/api/patients
Content-Type: application/json
{
  "firstName": "TestInDanger",
  "lastName": "Test",
  "dateOfBirth": "2004-06-18",
  "gender": "Homme",
  "address": "3 Club Road",
  "phoneNumber": "300-444-5555"
}
###
POST {{Back_HostAddress}}/api/patients
Content-Type: application/json
{
  "firstName": "TestEarlyOnset",
  "lastName": "Test",
  "dateOfBirth": "2002-06-28",
  "gender": "Femme",
  "address": "4 Valley Dr",
  "phoneNumber": "400-555-6666"
}
###
GET {{Back_HostAddress}}/api/patients/